# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevCleaner < Formula
  desc "Clean development artifacts on macOS - Xcode, Gradle, node_modules"
  homepage "https://github.com/thanhdevapp/mac-dev-cleaner-cli"
  version "1.0.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/thanhdevapp/mac-dev-cleaner-cli/releases/download/v1.0.3/dev-cleaner_1.0.3_darwin_amd64.tar.gz"
      sha256 "b21ad5e16341332de222f7ff290ef55105f89b55a9fdcf0f619be4366bd5d4f0"

      def install
        bin.install "dev-cleaner"
      end
    end
    on_arm do
      url "https://github.com/thanhdevapp/mac-dev-cleaner-cli/releases/download/v1.0.3/dev-cleaner_1.0.3_darwin_arm64.tar.gz"
      sha256 "d132d945793befadcc2a9fa0e64a036a5922e91cd9c61b5581f121bb9485c1cc"

      def install
        bin.install "dev-cleaner"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thanhdevapp/mac-dev-cleaner-cli/releases/download/v1.0.3/dev-cleaner_1.0.3_linux_amd64.tar.gz"
        sha256 "2c83c22c3e45ba4237e55e2e59cdbbbfd4725f36178166e4f08bd9a4da7237e3"

        def install
          bin.install "dev-cleaner"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thanhdevapp/mac-dev-cleaner-cli/releases/download/v1.0.3/dev-cleaner_1.0.3_linux_arm64.tar.gz"
        sha256 "2945bc6bc24106cfe6107912afa098d46fd2dfc3d3a946d7c0e2bb68f4f6ba48"

        def install
          bin.install "dev-cleaner"
        end
      end
    end
  end

  test do
    system "#{bin}/dev-cleaner", "--version"
  end
end
