# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevCleaner < Formula
  desc "Clean development artifacts on macOS - Xcode, Gradle, node_modules"
  homepage "https://github.com/thanhdevapp/mac-dev-cleaner-cli"
  version "1.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/thanhdevapp/mac-dev-cleaner-cli/releases/download/v1.0.1/dev-cleaner_1.0.1_darwin_amd64.tar.gz"
      sha256 "d1bc19f8c7f6200da07d5d6dc4eb50b3d017ff541da3750b87f7fdf78b127a52"

      def install
        bin.install "dev-cleaner"
      end
    end
    on_arm do
      url "https://github.com/thanhdevapp/mac-dev-cleaner-cli/releases/download/v1.0.1/dev-cleaner_1.0.1_darwin_arm64.tar.gz"
      sha256 "09be4087cd16dfa9a103ffcf2f3175d7eee6e457ad100f87252d46d89080be10"

      def install
        bin.install "dev-cleaner"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thanhdevapp/mac-dev-cleaner-cli/releases/download/v1.0.1/dev-cleaner_1.0.1_linux_amd64.tar.gz"
        sha256 "5c65d84163999a2b3c381ebee45ccc71b571aa375b88ebbbe32df673b2596774"

        def install
          bin.install "dev-cleaner"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thanhdevapp/mac-dev-cleaner-cli/releases/download/v1.0.1/dev-cleaner_1.0.1_linux_arm64.tar.gz"
        sha256 "7f7cd308ac518f373359eaa3b3033729a6c420df247b7a56b967c1d7f2cab3a8"

        def install
          bin.install "dev-cleaner"
        end
      end
    end
  end

  test do
    system "#{bin}/dev-cleaner", "--version"
  end
end
