# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevCleaner < Formula
  desc "Clean development artifacts on macOS - Xcode, Gradle, node_modules"
  homepage "https://github.com/thanhdevapp/mac-dev-cleaner-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/thanhdevapp/mac-dev-cleaner-cli/releases/download/v1.0.0/dev-cleaner_1.0.0_darwin_amd64.tar.gz"
      sha256 "874c5bdd4952537a0a93cf1dc53cd5ac50275bf8c2f7609414f1232f3152e642"

      def install
        bin.install "dev-cleaner"
      end
    end
    on_arm do
      url "https://github.com/thanhdevapp/mac-dev-cleaner-cli/releases/download/v1.0.0/dev-cleaner_1.0.0_darwin_arm64.tar.gz"
      sha256 "9fbdf4c9b0d534d3f65d137397a6b40f99ffb5523970270c98e0145f087a3c8f"

      def install
        bin.install "dev-cleaner"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thanhdevapp/mac-dev-cleaner-cli/releases/download/v1.0.0/dev-cleaner_1.0.0_linux_amd64.tar.gz"
        sha256 "3937746c78563f473333c78670366e5a171f61bd454048b5299871157165efda"

        def install
          bin.install "dev-cleaner"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thanhdevapp/mac-dev-cleaner-cli/releases/download/v1.0.0/dev-cleaner_1.0.0_linux_arm64.tar.gz"
        sha256 "915b24b98452953b546ba34ac8cb8b033208b48f5f16e20d92c9d5d5b4b86c3b"

        def install
          bin.install "dev-cleaner"
        end
      end
    end
  end

  test do
    system "#{bin}/dev-cleaner", "--version"
  end
end
